AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  AWSLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../../lambda/lambdaFunction
      Description: ''
      MemorySize: 128
      Timeout: 30
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          ENVIRONMENT: dev
          LOGGING_LEVEL: DEBUG
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Layers:
        - !Ref lambdaLayer
      PackageType: Zip

  lambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../../../layers/lambdaLayer/lambdaLayer.zip
      LayerName: lambdaLayer
      CompatibleRuntimes:
        - python3.12
